language: cpp
# run on new infrastructure
sudo: false
cache: apt
# required packages to install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - help2man
      - python-pexpect
      - libusb-1.0-0-dev
      - device-tree-compiler

env:
  global:
    - RISCV="/home/travis/riscv_install"
    - MAKEFLAGS="-j2"
    - PATH="/home/travis/riscv_install/bin:$PATH"
    - CROSSTOOL_VERSION=1.24.0-rc3

before_install:
  # make install destination
  - mkdir -p $RISCV
  # don't forget to clone riscv-tests/env
  - cd riscv-tests
  - git submodule update --init
  - cd ..
  # openocd also needs submodules
  - cd riscv-openocd
  - git submodule update --init
  - cd ..
  - unset CC CXX

# extra time duing long builds
install: travis_wait

# pexpect ends up in /usr/lib/python2.7/dist-packages, which is not part of the
# default python path.
script:
  - mkdir ~/src
  - curl http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-$CROSSTOOL_VERSION.tar.xz | tar -xJp
  - cd crosstool-ng-$CROSSTOOL_VERSION; ./configure --prefix=$RISCV; cd ..
  - make -C crosstool-ng-$CROSSTOOL_VERSION
  - make -C crosstool-ng-$CROSSTOOL_VERSION install
  - ct-ng riscv64-unknown-elf
  - travis_wait 30 ct-ng build
  - ./build.sh
  - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages make -C riscv-tests/build debug-check
